#!/bin/bash

########################  FUNCTIONS

file=${_PATH_BASE}/perso/inc
! [ -f "${file}" ] && _exite "Unable to find file: ${file}"
! . ${file} && _exite "Errors while sourcing file: ${file}. See log files in /var/log/foralyse"

########################  SUB

_source_perso conf
#source_perso firefox
#_source_perso sublimetext
#_source_perso sublimemerge

_echoa "\n-----------------------------------------------"
_echoA "End of part perso"
