#!/bin/bash

_echot "------- dconf screensave"
_eval "dconf write /org/gnome/desktop/screensaver/lock-delay 'uint32 3600'"

_echot "------- dconf gnome-terminal"
_menu "Select the gnome-terminal profiles file to import" none $(cd ${_path_base}/conf/soft && ls gnome-terminal-profiles*)
[ ${_ANSWER} != none ] && _eval "dconf load /org/gnome/terminal/legacy/profiles:/ < ${_path_base}/conf/soft/${_ANSWER}"

