#!/bin/bash

_echot "------- python"
packages="python3 python3-pip python3-pipx"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

packages="yt-dlp"
for package in ${packages}; do
	_echot "------- pipx"
	_evalr pipx install ${package}
done

