#!/bin/bash

_echot "------- gnome-shell-extensions"
packages="gnome-shell-extension-manager"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- extensions"
_echoA "Choose extensions to install like:"
_echoA "  Dash to Dock"
_echoA "  User Themes"
_echoA "  Vitals"
_askno "Validate to choose"
extension-manager

