#!/bin/bash

########################  REMOVE

_echot "------- firefox remove snap"
_evalr snap remove --purge firefox

_echot "------- firefox remove"
_evalr apt remove -y --purge firefox*

########################  FIREFOX

_echot "------- block snap"
echo 'Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1000' | sudo tee /etc/apt/preferences.d/mozillateam

_echot "------- firefox add ppa"
_evalr add-apt-repository -yn ppa:mozillateam/ppa

_echot "------- apt update"
_evalr apt update

_echot "------- firefox install"
_install_pcks firefox

_echot "------- firefox profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
firefox --ProfileManager

_echot "------- firefox user.js"
pth=${HOME}/.mozilla/firefox/${USER}
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_keepmvts ${pth}/user.js
_eval ln -s "${S_PATH_SCRIPT}/conf/user.js" ${pth}/user.js
_evalr chown ${USER}:${USER} ${pth}

_echot "------- firefox launcher"
name=firefox
file=/usr/share/applications/${name}.desktop
pth=~/.local/share/applications
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;ProfileUser;ProfileManager;SafeMode;Separator;FirefoxDev;Chromium;Separator;Qarte;aMule;"
		sed -i "s/^\(Actions=.*\)$/\1${menuadd}/" ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action ProfileUser]
Name=Profile ubuntu
Exec=firefox -P ubuntu

[Desktop Action SafeMode]
Name=Safe Mode
Exec=firefox --safe-mode

[Desktop Action ProfileManager]
Name=Profile Manager
Exec=firefox --ProfileManager

[Desktop Action Thunderbird]
Name=Thunderbird
Exec=thunderbird

[Desktop Action FirefoxDev]
Name=Firefox Developper Edition
Exec=firefox-dev -P ubuntu-dev

[Desktop Action Chromium]
Name=Chromium browser
Exec=chromium-browser

[Desktop Action Qarte]
Name=Qarte
Exec=qarte

[Desktop Action aMule]
Name=aMule
Exec=amule

[Desktop Action Skype]
Name=Skype
Exec=skype %U

[Desktop Action Pidgin]
Name=Pidgin
Exec=pidgin
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

########################  THUNDERBIRD

_echot "------- thunderbird install"
_evalr apt  install -y thunderbird

_echot "------- thunderbird profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
thunderbird --ProfileManager

_echot "------- thunderbird launcher"
name=thunderbird
file=/usr/share/applications/${name}.desktop
pth=~/.local/share/applications
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Separator;Addressbook;ProfileManager;ProfileExtend;"
		sed -i "s/^\(Actions=.*\)$/\1${menuadd}/" ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Addressbook]
Name=Addressbook
Exec=thunderbird -addressbook

[Desktop Action ProfileManager]
Name=Profile Manager
Exec=thunderbird --ProfileManager

[Desktop Action ProfileExtend]
Name=Profile  Extend
Exec=thunderbird -P extend
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

########################  LANGUAGES

_echot "------- languages"
_echoA "Close language window after validation."
_askno "Validate to continue"
gnome-language-selector


