#!/bin/bash

########################  LINKS

while ps -ax | grep -q '[f]irefox'; do _askno "Please close Firefox application and validate"; done
while ps -ax | grep -q '[t]hunderbird'; do _askno "Please close Thunderbird application and validate"; done

cd ${HOME}
nopart=

pth_to_init=/home/shared
echo "================ ${pth_to_init}"
pths=".mozilla.${_VER_NAME:0:3} .thunderbird.${_VER_NAME:0:3}"
_echoa ${pths}
_askno "Give a new list or valid the subdirectories list above to link to ${pth_to_init}"
[ "${_ANSWER}" ] && pths=${_ANSWER}

for pth in ${pths}; do
	msg=
	pth_from=${pth%\.*}
	pth_to=${pth_to_init}/${pth}
	echo -n "${pth_from} "
	if [ -e ${pth_to} ]; then
		[ -h ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
		[ -f ${pth_from} ] && echo rm ${pth_from} && rm ${pth_from}
		[ -d ${pth_from} ] && { rmdir ${pth_from} || msg="path is not empty"; }
		if [ -e ${pth_from} ]; then
			_echoe "- !!! failed !!! ${msg}"
			nopart=exit
		else
			ln -s ${pth_to} ${pth_from}
			echo "- ok"
		fi
	else
		_echoe "- *** skipped *** ${pth_to} is missing"
	fi
done

[ "${nopart}" ] && _exite "Please restart due to some errors"

########################  REMOVE

_echot "------- firefox remove snap"
_evalr snap remove --purge firefox

_echot "------- firefox remove"
_evalr apt remove -y --purge firefox*

########################  FIREFOX

_echot "------- block snap"
echo 'Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1000' | sudo tee /etc/apt/preferences.d/mozillateam

_echot "------- firefox add ppa"
_evalr add-apt-repository -yn ppa:mozillateam/ppa

_echot "------- apt update"
_evalr apt update

_echot "------- apt ugrade"
_evalr apt upgrade -y

_echot "------- firefox install"
_install_pcks firefox

_echot "------- firefox profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
firefox --ProfileManager

_echot "------- user.js"
pth=${HOME}/.mozilla/firefox/${USER}
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_keepmvts ${pth}/user.js
_eval ln -s "${_PATH_BS}/conf/user.js" ${pth}/user.js
_evalr chown ${USER}:${USER} ${pth}

########################  THUNDERBIRD

_echot "------- thunderbird install"
_evalr apt  install -y thunderbird

_echot "------- thunderbird profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
thunderbird --ProfileManager

########################  LANGUAGES

_echot "------- languages"
_echoA "Close language window after validation."
_askno "Validate to continue"
gnome-language-selector
