#!/bin/bash

########################  REQUIRED

file_mudita=${_path_base}/perso/xtra/Mudita24.desktop
_require ${file_mudita}

_echot "------- install"
packages="mudita24"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install packages: ${packages}"; return 1; }

_echot "------- launcher"
pth=~/.config/autostart
_keepmvts ${pth}/${file_mudita##*/}
[ -d ${pth} ] || _eval mkdir ${pth}
_eval cp -a ${file_mudita} ${pth}

_echot "------- configuration"
_echoA "Please adjust volumes and routes and save profile after vaildation."
_askno "Validate to continue"
_eval mudita24 -p4

