#!/bin/bash

########################  REQUIRED

_echot "------- required files"
file_env=${_path_base}/bs/conf/.sh_env
file_sh_aliases=${_path_base}/bs/conf/.sh_aliases
file_sh_functions=${_path_base}/bs/conf/.sh_functions
_require ${file_env} ${file_sh_aliases} ${file_sh_functions}

########################  MAIN

_echot "------- .sh_env"
file=/root/.sh_env
[ -h ${file} ] && _evalr rm ${file}
_keepmvts ${file}
_evalr ln -s ${file_env} ${file}

_echot "------- .sh_aliases"
file=/root/.sh_aliases
[ -h ${file} ] && _evalr rm ${file}
_keepmvts ${file}
_evalr ln -s ${file_sh_aliases} ${file}

_echot "-------  .sh_functions"
file=/root/.sh_functions
[ -h ${file} ] && _evalr rm ${file}
_keepmvts ${file}
_evalr ln -s ${file_sh_functions} ${file}

_echot "------- common .*hrc"
for file in /root/.bashrc /root/.zshrc; do
	_keepcpts ${file}
	grep -sq '####  PERSO' ${file} || echo "
########################  PERSO

PS1='\[\033[01;31m\]\u@\h \[\033[1;37m\]\W\[\033[01;31m\]\$\[\033[00m\] '

# HISTORY
HISTSIZE=50000
HISTFILESIZE=50000

# source global variables
[ -f ~/.sh_env ] && . ~/.sh_env

# aliases
[ -f ~/.sh_aliases ] && . ~/.sh_aliases

# functions
[ -f ~/.sh_functions ] && . ~/.sh_functions" | sudo tee -a ${file}
done

_echot "------- .zshrc"
echo "
########################  SET OPTIONS

# split words in string with default delimiters ' '
setopt shwordsplit
# allows interactive comments in console
setopt interactivecomments
" | sudo tee -a /root/.zshrc

# force color
sudo sed -i '/^#force_color_prompt=/ s|#||' ${file}

_echot "------- .vimrc"
file=/root/.vimrc
file_from=${_PATH_BS}/conf/.vimrc
_keepmv ${file}
_evalr ln -s ${file_from} ${file}
