#!/bin/bash

########################  REQUIRED

_echot "------- required paths"
pth_conf=${_path_base}/perso/conf
_requirep ${pth_conf}

########################  DATA

anstmp=9
_askno "Give the size for desktop font (${anstmp})"
font_size=${_ANSWER:-${anstmp}}

anstmp=3600
_askno "Give the screensaver lock-delay inseconds (${anstmp})"
screen_lock_delay=${_ANSWER:-${anstmp}}

########################  MAIN

_echot "------- dconf gnome-terminal"
_menu "Select the gnome-terminal profiles file to import" none $(cd ${pth_conf} && ls gnome-terminal-profiles*)
[ ${_ANSWER} != none ] && _eval "dconf load /org/gnome/terminal/legacy/profiles:/ < ${pth_conf}/${_ANSWER}"
# dconf dump /org/gnome/terminal/legacy/profiles:/ > ${pth_conf}/${_ANSWER}
# gsettings get org.gnome.Terminal.ProfilesList list
# gsettings get org.gnome.Terminal.ProfilesList default

_echot "------- gsettings keyboard"
options="delay 'uint32 300'
numlock-state true
repeat-interval 20"
while read key value; do
_eval "gsettings set org.gnome.desktop.peripherals.keyboard ${key} ${value}"
done <<< "$options"

_echot "------- gsettings font-size"
_eval "gsettings set org.gnome.desktop.interface document-font-name 'Sans ${font_size}'"
_eval "gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace ${font_size}'"

_echot "------- gsettings"
_eval "gsettings set org.gnome.desktop.interface clock-format '24h'"
_eval "gsettings set org.gnome.desktop.interface clock-show-weekday true"

_echot "------- gsettings screensaver"
_eval "gsettings set org.gnome.desktop.screensaver lock-delay 'uint32 ${screen_lock_delay}'"

_echot "------- gsettings dock"
options="always-center-icons true
background-opacity 0
dock-fixed false
dock-position 'BOTTOM'
scroll-action 'cycle-windows'
transparency-mode 'FIXED'"
while read key value; do
	_eval "gsettings set org.gnome.shell.extensions.dash-to-dock ${key} ${value}"
done <<< "$options"

