#!/bin/bash

########################  REQUIRED

_echot "------- required paths"
pth_conf=${_path_base}/perso/conf
_requirep ${pth_conf}

########################  DATA

anstmp=9
_askno "Give the size for global desktop font (${anstmp})"
font_size=${_ANSWER:-${anstmp}}

let anstmp=${font_size}+1
_askno "Give the size for global desktop font (${anstmp})"
font_interface_size=${_ANSWER:-${anstmp}}

anstmp=3600
_askno "Give the screensaver lock-delay inseconds (${anstmp})"
screen_lock_delay=${_ANSWER:-${anstmp}}

########################  DESKTOP

_echot "------- gsettings desktop"
_eval "gsettings set org.gnome.desktop.interface font-name 'Ubuntu Sans ${font_interface_size}'"
_eval "gsettings set org.gnome.desktop.interface document-font-name 'Sans ${font_size}'"
_eval "gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace ${font_size}'"

_eval "gsettings set org.gnome.desktop.interface clock-format '24h'"
_eval "gsettings set org.gnome.desktop.interface clock-show-weekday true"

_eval "gsettings set org.gnome.desktop.screensaver lock-delay 'uint32 ${screen_lock_delay}'"

_eval "gsettings set org.gnome.desktop.sound event-sounds false"

########################  TERMINAL

_echot "------- dconf gnome-terminal"
_menu "Select the gnome-terminal profiles file to import" none $(cd ${pth_conf} && ls gnome-terminal-profiles*)
[ ${_ANSWER} != none ] && _eval "dconf load /org/gnome/terminal/legacy/profiles:/ < ${pth_conf}/${_ANSWER}"
# dconf dump /org/gnome/terminal/legacy/profiles:/ > ${pth_conf}/${_ANSWER}
# gsettings get org.gnome.Terminal.ProfilesList list
# gsettings get org.gnome.Terminal.ProfilesList default

########################  KEYBOARD

_echot "------- gsettings keyboard"
options="delay 'uint32 300'
numlock-state true
repeat-interval 20"
while read key value; do
	_eval "gsettings set org.gnome.desktop.peripherals.keyboard ${key} ${value}"
done <<< "$options"

########################  DOCK

_echot "------- gsettings dock"
options="always-center-icons true
background-opacity 0
dock-fixed false
dock-position 'BOTTOM'
scroll-action 'cycle-windows'
show-trash false
transparency-mode 'FIXED'"
while read key value; do
	_eval "gsettings set org.gnome.shell.extensions.dash-to-dock ${key} ${value}"
done <<< "$options"

########################  NAUTILUS

_echot "------- gsettings nautilus"
_eval "gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'"
_eval "gsettings set org.gnome.nautilus.list-view use-tree-view true"
_eval "gsettings set org.gnome.nautilus.compression default-compression-format 'tar.xz'"

options="default-folder-viewer 'list-view'
show-create-link true
show-delete-permanently true
show-hidden-files true"
while read key value; do
	_eval "gsettings set org.gnome.nautilus.preferences ${key} ${value}"
done <<< "$options"

########################  MELD

_echot "------- gsettings meld"
options="highlight-current-line true
indent-width 4
prefer-dark-theme true
show-line-numbers true
show-overview-map true
style-scheme 'meld-dark-perso'"
while read key value; do
	_eval "gsettings set org.gnome.meld ${key} ${value}"
done <<< "$options"

########################  WM

_echot "------- gsettings vim"
options="audible-bell false
titlebar-font 'Ubuntu Sans Bold 11'"
while read key value; do
	_eval "gsettings set org.gnome.desktop.wm.preferences ${key} ${value}"
done <<< "$options"

########################  GTK

_echot "------- gsettings gtk"
_eval "gsettings set org.gtk.Settings.FileChooser expand-folders true"
_eval "gsettings set org.gtk.Settings.FileChooser show-hidden true"

########################  OTHERS

_echot "------- gsettings others"
_eval "gsettings set org.gnome.mutter center-new-windows true"
