#!/bin/bash

########################  SYSTEM

_echot "------- conf sources"
# Change the mirror of software sources
_evalr pacman-mirrors --country-list
_evalr pacman-mirrors -c France

_echot "------- create paths"
paths="ext/backup ext/ovh ext/shared /home/shared"
for path in ${paths}; do
	[ -d "${path}" ] || _evalr mkdir -p ${path}
	_evalr chown ${USER}:${USER} ${path}
done

########################  USER

_echot "------- .bash_env"
file=${HOME}/.bash_env
file_from=${_PATH_BS}/conf/.bash_env
_keepmv ${file}
_eval ln -s ${file_from} ${file}
_eval sed -i "s|_PATH_BS|${_PATH_BS}|" ${file_from}

_echot "------- .bashrc env"
file=${HOME}/.bashrc
grep -q ".bash_env" ${file} || echo "
# global variables
[ -f \${HOME}/.bash_env ] && . \${HOME}/.bash_env

# functions
[ -f \${HOME}/.bash_functions ] && . \${HOME}/.bash_functions" >> ${file}
. ${file}

_echot "------- firefox tweaks"
path=${HOME}/.mozilla/firefox/${USER}
if [ -d "${path}" ]; then
	_eval ln -s "${_PATH_BS}/conf/user.js" ${path}
	_eval chown ${USER}:${USER} ${path}
fi
