#!/bin/bash

_echoT "#################### START ${_PARTDEV}"

########################  DATA

path_opt=/opt/eclipse_${_ECLIPSE_THEME}
path_conf=.eclipse_${_ECLIPSE_THEME}
path_desk=~/.local/share/applications
path_proj=${HOME}/dev/eclipse-workspaces-${_ECLIPSE_THEME}
file_desk=${path_desk}/eclipse_java.desktop
file_bin=/usr/bin/eclipse_${_ECLIPSE_THEME}

file_desk_conf=${_PATH_BASE}/conf/eclipse_${_ECLIPSE_THEME}.desktop

_require ${file_desk_conf}

########################  MAIN

_echot "------- backup"
paths=
if [ -d "${path_opt}" ] || [ -d ~/${path_conf} ] || [ -d "${path_proj}" ]; then
	for path in ${path_opt} ~/${path_conf} ${path_proj} ${file_desk} ${file_bin}; do
		[ -e "${path}" ] && paths+=" ${path}"
	done
	tar czf ${_PATH_SOFT_BACKUP}/eclipse_${_ECLIPSE_THEME}_backup_${_DATE}-$(date +%s).tar.gz ${path_opt} ${paths}
fi

_echot "------- clean instance"
# delete existing folder
for path in ${path_opt} ~/${path_conf} ${path_proj} ${file_desk} ${file_bin}; do
	[ -e "${path}" ] && _evalr rm -fR ${path}
done

####################  RESTORE

if [ "${_ECLIPSE_DATE}" ]; then

	[ -h ~/dev ] || ln -s /home/shared/dev ~/dev
	${S_PATH_SCRIPT}/backup-soft --restore ${_ECLIPSE_DATE} eclipse_${_ECLIPSE_THEME} --force

####################  FRESH INSTALL

elif [ "${_ECLIPSE_VER}" ]; then

	_echot "------- create path"
	for path in ${path_opt} ~/${path_conf} ${path_proj}; do
		[ -d "${path}" ] || _evalr mkdir -p ${path}
		chown 1000:1000 "${path}"
	done

	cd /tmp

	_echot "------- get"

	file=eclipse-java-${_ECLIPSE_VER}-R-linux-gtk-x86_64.tar.gz
	url=http://mirror.ibcp.fr/pub/eclipse//technology/epp/downloads/release/${_ECLIPSE_VER}/R/${file}

	if [ -f "${_PATH_SOFT}/${file}" ]; then
		cp ${_PATH_SOFT}/${file} .
	else
		_ANSWER=${file}
		while ! curl -o "$_ANSWER" "$url"; do
			_ask "Unable to donwload:\n$url\nGive a good url to download ${file}\nConfirm"
		done
		_evalr cp ${file} ${_PATH_SOFT}/
	fi

	_echot "------- install"
	path=eclipse
	[ -d "${path}" ] && rm -fR ${path}
	_eval tar xzf ${file}
	_evalr mv ${path} ${path_opt}
	rm ${file}

	_echot "------- ${file_bin} bind"
	sudo [ -e "${file_bin}" ] && _evalr rm ${file_bin}
	_evalr ln -s ${path_opt}/eclipse ${file_bin}

	_echot "------- launcher"
	_eval cp ${file_desk_conf} ${file_desk}
	chmod +x ${file_desk}

fi

####################  COMMON

_echot "------- conf"
file=${path_opt}/eclipse.ini
_keepcd ${file}
grep -q '^-Duser' ${file} || sed -i "/^-vmargs/ a-Duser.home=${HOME}/.eclipse_${_ECLIPSE_THEME}" ${file}
sed -i "/^-Dosgi.instance.area.default/ s|=.*|=${path_proj}/init|" ${file}
#sed -i "/^-Dosgi.instance.area.default/ s|=.*|=${path_proj}/eclipse-workspaces-${_ECLIPSE_THEME}|" ${file}

_echot "------- jdk src doc"
_CMD_INS openjdk-21-source openjdk-21-doc

_echoT "#################### END ${_PARTDEV}"

<<KEEP
####  marketplace

https://marketplace.eclipse.org/content/bash-editor
https://marketplace.eclipse.org/content/jenkins-editor

http://www.eclipsecolorthemes.org


####  dev

# pydev
http://pydev.org/updates
# basheditor
https://dl.bintray.com/de-jcup/basheditor
# devstyle
http://www.genuitec.com/updates/devstyle/ci
# quickrex
http://netceteragroup.github.io/quickrex/updatesite
# dev-utils
http://kangtae49.github.io/dev-utils-plugin/update


####  modeling

# remove
gradle
EclEmma
Java development tools
justJ
m2e maven
POM
TM terminal
WWW

####  add
efxclipse
GEF dot

# color theme
http://eclipse-color-theme.github.io/update/

# dbeaver
https://dbeaver.io/update/latest/

# Papyrus
https://download.eclipse.org/modeling/mdt/papyrus/updates/releases/2021-09
https://download.eclipse.org/modeling/mdt/papyrus/updates/nightly/master
# SysML16
https://download.eclipse.org/modeling/mdt/papyrus/components/sysml16/2021-09
# Papyrus Software designer
http://download.eclipse.org/modeling/mdt/papyrus/components/designer/2.0.0


##### others

# Apache Directory Studio
http://directory.apache.org/studio/update/2.x

# Polarion
http://www.polarion.com/products/svn/subversive/download.php
## SVN connectors polarion
http://community.polarion.com/projects/subversive/download/eclipse/4.0/update-site/
http://community.polarion.com/projects/subversive/download/eclipse/4.0/luna-site/
## SVN Plugins integration
http://community.polarion.com/projects/subversive/download/integrations/luna-site/
http://download.eclipse.org/technology/subversive/2.0/update-site/

# SQLexplorer
http://eclipsesql.sourceforge.net/

# RSE (ftp)
http://download.eclipse.org/dsdp/tm/updates/3.0/

# Bastian-Bergerhoff
http://www.bastian-bergerhoff.com/eclipse/features

# Esftp
http://sourceforge.net/projects/esftp/

# connectors
    * DB2
          o Driver Class: COM.ibm.db2.jdbc.app.DB2Driver
          o Connection URL: jdbc:db2:
          o Driver .jar/.zip: db2java.zip
    * Sybase
          o Driver Class: com.sybase.jdbc2.jdbc.SybDriver
          o Connection URL: jdbc:sybase:Tds::/
          o Driver .jar/.zip: jconn2.jar
    * Oracle
          o Driver Class: oracle.jdbc.driver.OracleDriver
          o Connection URL: jdbc:oracle:thin:@ ::
          o Driver .jar/.zip: classes12.zip
    * SQLServer
          o Driver Class: com.microsoft.jdbc.sqlserver.SQLServerDriver
          o Connection URL: jdbc:microsoft:sqlserver://localhost:1433
          o Driver .jar/.zip: mssqlserver.jar, msbase.jar, msutil.jar
    * PostgreSQL
          o Driver Class: org.postgresql.Driver
          o Connection URL: jdbc:postgresql://
KEEP
